platform :ios, '9.0'

target 'Bliss-Assignement' do
  use_frameworks!

  # Pods for Bliss-Assignement
  pod 'Alamofire', '~> 3.0'
  pod 'AlamofireImage', '~> 2.5'
  pod 'AlamofireNetworkActivityIndicator', '~> 1.1'
  pod 'JGProgressHUD'

end

# Set dependencies to compile with legacy swift 2.3
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
